### ISSUE TITLE
Doesn't work, blank canvas when launching

### ISSUE THREAD

**Issue by jsardev** [blopker/alic#2]
Hey! I wanted to try out `alic` but unfortunately it doesn't work for me. When I launch it it looks like this:

![CleanShot 2024-04-04 at 08 26 12](https://github.com/blopker/alic/assets/11553624/314f6efd-fa08-48e9-b9b3-274c85871ac5)

Any ideas what's wrong? 🤔

MacOS Sonoma 14.1

**Comment by blopker** [comment]
Oh no! Thanks for the report. Clearly it's the, erm, yeah, the app isn't telling us much. Are you on an Intel chip, or M*?
