### ISSUE TITLE
Support for `Open with` & `Drop on Dock`

### ISSUE THREAD

**Issue by chrisspiegl** [blopker/alic#3]
I just found this linked in an ImageOptim issue and thought it was interesting to have an alternative and slightly different approach.

I wonder if you could add `Open with` & `Drop on Dock` support to this application for easier processing and ability to itegrate into workflows or throw fiels into Alic with apps like Alfred.

**Comment by blopker** [comment]
Hey! Excellent ideas. I'll take a look next time I have a chance.

**Comment by blopker** [comment]
Hey! I was able to get both `Open with` and drop on dock working in the latest version (1.5.0). Thanks for the suggestion :)

**Comment by chrisspiegl** [comment]
Looking good. I'll take another look and maybe it will replace my ImageOptim workflow 👍.
