### ISSUE TITLE
Image Resize Settings in Interface

### ISSUE THREAD

**Issue by chrisspiegl** [blopker/alic#4]
I like that this app includes an option to resize files. A few improvement ideas on that front:

## Shortcut / Button to Jump to the Resize Setting

This would be helpful to adjust this setting on the fly and easily make changes.

## Shortcut / Button to enable/disable Resizing

Having this on the home screen of the app would make it easy to use / not use the resizing.

## Display Resize Sizes on Home Screen

Currently, it displays `resizing images` in the status bar. But it's lacking the size that is set. Not a problem if you always use the same setting. But if you need to change it, sometimes it's easy to miss and have the wrong setting.

**Comment by blopker** [comment]
Interesting ideas. I always keep it on the same size, so it hasn't been an issue for me. Are you often changing the resize dimensions? If so, are you changing the dimensions to different values all the time, or are there common values that you change between?

Another approach could be to have different setting profiles, with a profile switcher.

**Comment by chrisspiegl** [comment]
I could see myself switching between a 720p version 1080p and 4k for example.

I did think that presets would be an interesting idea but didn't want to run through the wall with that right away.

**Comment by blopker** [comment]
Hey, I wanted to follow up on this. I've released version 2, which was a rewrite to support multiple profiles. Thanks for the suggestion. :)

**Comment by chrisspiegl** [comment]
The development here looks promising. I like the new featuers with the presets, improvements, open with, etc. Thank you 🌻.
