### ISSUE TITLE
remove white space scrollbar

### ISSUE THREAD

**Issue by heyadeivan** [blopker/alic#6]
I see a white space, I think it's a scrollbar, it's so distracting.
<img width="712" alt="Screenshot 2024-12-22 at 13 25 15" src="https://github.com/user-attachments/assets/3592be63-017f-4528-9936-1299a0274c11" />

**Comment by blopker** [comment]
Hey, thank you for the report. I haven't seen it do that before. Could you tell me a bit about your system? What macos version are you on, what version of Safari? Is there anything non standard about your system, like different font settings?

**Comment by blopker** [comment]
Ok, I've been able to reproduce it. Setting "Show scroll bars" to "Always" makes this happen. Looking for a good fix.

**Comment by blopker** [comment]
This is fixed in 2.0.8 :)
